spring.application.name=nexus-importer

spring.config.import=optional:file:../docker/.env[.properties],optional:file:docker/.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nexus}
spring.datasource.username=${DB_USERNAME:${POSTGRES_USER:nexus}}
spring.datasource.password=${DB_PASSWORD:${POSTGRES_PASSWORD:}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false


nexus.importer.input-directory=${NEXUS_IMPORTER_INPUT_DIRECTOR}
nexus.importer.enabled=${NEXUS_IMPORTER_ENABLED:true}
nexus.importer.scan-delay=${NEXUS_IMPORTER_SCAN_DELAY:30m}
nexus.importer.initial-delay=${NEXUS_IMPORTER_INITIAL_DELAY:10s}
nexus.importer.minimum-file-age=${NEXUS_IMPORTER_MINIMUM_FILE_AGE:2m}

nexus.importer.source-time-zone=${NEXUS_IMPORTER_SOURCE_TIME_ZONE:Africa/Casablanca}
nexus.importer.measurement-batch-size=${NEXUS_IMPORTER_MEASUREMENT_BATCH_SIZE:500}
