services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: nexus-postgres

    env_file:
      - .env

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - nexus_postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nexus-redis

    ports:
      - "${REDIS_PORT}:6379"

    restart: unless-stopped

volumes:
  nexus_postgres_data: