spring.application.name=nexus-api

spring.config.import=optional:file:../docker/.env[.properties],optional:file:docker/.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nexus}
spring.datasource.username=${DB_USERNAME:${POSTGRES_USER:nexus}}
spring.datasource.password=${DB_PASSWORD:${POSTGRES_PASSWORD:}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
